// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cluster is the predicate function for cluster builders.
type Cluster func(*sql.Selector)

// Component is the predicate function for component builders.
type Component func(*sql.Selector)
