// Code generated by entc, DO NOT EDIT.

package cluster

import (
	"time"
)

const (
	// Label holds the string label denoting the cluster type in the database.
	Label = "cluster"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClusterID holds the string denoting the cluster_id field in the database.
	FieldClusterID = "cluster_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClusterType holds the string denoting the cluster_type field in the database.
	FieldClusterType = "cluster_type"
	// FieldClusterSpec holds the string denoting the cluster_spec field in the database.
	FieldClusterSpec = "cluster_spec"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// FieldRegionID holds the string denoting the region_id field in the database.
	FieldRegionID = "region_id"
	// FieldVpcID holds the string denoting the vpc_id field in the database.
	FieldVpcID = "vpc_id"
	// FieldZoneID holds the string denoting the zone_id field in the database.
	FieldZoneID = "zone_id"
	// FieldEnableDeletionProtection holds the string denoting the enable_deletion_protection field in the database.
	FieldEnableDeletionProtection = "enable_deletion_protection"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the cluster in the database.
	Table = "clusters"
)

// Columns holds all SQL columns for cluster fields.
var Columns = []string{
	FieldID,
	FieldClusterID,
	FieldName,
	FieldClusterType,
	FieldClusterSpec,
	FieldVersion,
	FieldProfile,
	FieldRegionID,
	FieldVpcID,
	FieldZoneID,
	FieldEnableDeletionProtection,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultClusterType holds the default value on creation for the "cluster_type" field.
	DefaultClusterType string
	// DefaultProfile holds the default value on creation for the "profile" field.
	DefaultProfile string
	// DefaultEnableDeletionProtection holds the default value on creation for the "enable_deletion_protection" field.
	DefaultEnableDeletionProtection bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
