apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f deploy/docker-compose/docker-compose.yaml -o deploy/kubernetes
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cluster-admin
  name: cluster-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cluster-admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f deploy/docker-compose/docker-compose.yaml -o deploy/kubernetes
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cluster-admin
    spec:
      containers:
        - image: ecloud.io/multicluster-admin:0.1.0
          name: cluster-admin
          ports:
            - containerPort: 81
          resources: {}
      restartPolicy: Always
status: {}
