apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f deploy/docker-compose/docker-compose.yaml -o deploy/kubernetes
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cluster-db
  name: cluster-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: cluster-db
status:
  loadBalancer: {}
